# Generated by Django 3.1.4 on 2021-03-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=50)),
                ('dog_gender', models.CharField(max_length=50)),
                ('dog_breed', models.CharField(max_length=50)),
                ('dog_weight', models.IntegerField(max_length=1000)),
                ('dog_age', models.CharField(max_length=50)),
                ('dog_city', models.CharField(max_length=50)),
                ('dog_state', models.CharField(max_length=50)),
                ('dog_owner_first', models.CharField(max_length=50)),
                ('dog_owner_last', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
